name: CI Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'

jobs:
  unit-testing:
    name: Unit Testing
    strategy:
      matrix:
        node_version: [18, 20]
        operating_system: [ubuntu-latest, macos-latest]
    
    runs-on: ${{ matrix.operating_system }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.4.0
        with:
          node-version: ${{ matrix.node_version }}

      - name: Install npm dependencies
        run: npm install

      - name: Run unit tests
        run: npm test